### ISSUE TITLE
JavaFX based client-browser enhancement interest

### ISSUE THREAD

**Issue by starksm64** [eclipse/californium.tools#13]
I'm interested in contributing a JavaFX variation of the cf-browser tools subproject. The initial prototype is visible in the current #12 pull request. I forgot that all changes pushed to a repo get merged into outstanding pull requests, so the change for the #11 issue. 

Anyway, I'm looking for feedback on whether this is of interest, and what changes need to be made up front to allow for its incorporation into the tools project. The main enhancements in addition to using javafx for simpler maintenance of the gui is to support viewing the log messages and initial work to display information about the response.
![screen1](https://cloud.githubusercontent.com/assets/332210/11910093/b8a0a9da-a5a4-11e5-8b60-c8c25efdca5c.png)
![screen2](https://cloud.githubusercontent.com/assets/332210/11910094/b8a13954-a5a4-11e5-9466-a292978f90b7.png)

Note that I work for Red Hat, so I'll have to figure out how to associate the correct git username and email for the CLA.

**Comment by mkovatsc** [comment]
Dear Scott, please excuse the long silence. This looks very neat and I think it should actually replace the current cf-browser project! Feel free to open a pull request.

**Comment by starksm64** [comment]
Ok, created https://github.com/eclipse/californium.tools/pull/20

**Comment by mkovatsc** [comment]
Merged.
Are you planning to continue working on it?

**Comment by starksm64** [comment]
Yes, now that is in the codebase I will

**Comment by mkovatsc** [comment]
Merged 6333629 in PR #20
