### ISSUE TITLE
cf-rd RD Lookup Classes use equality(==) instead of "instanceof" when comparing classes

### ISSUE THREAD

**Issue by calif-devel** [eclipse/californium.tools#15]
RD Lookup classes use logic like:
```java
if (res.getClass() == RDNodeResource.class) {
     RDNodeResource node = (RDNodeResource) res;
     :
}
```
which prevents extending RDNodeResource class for any custom implementation.  I tried extending RDNodeResource class for adding support to "et" end-point type attribute (Issue #14).  However when tried to test the look up feature, the above logic in class RDLookUpEPResource would fail for my custom class.

**Comment by mkovatsc** [comment]
Thanks for pointing that out!
