### ISSUE TITLE
Cf-CoAPBench fails to build

### ISSUE THREAD

**Issue by andreibosco** [eclipse/californium.tools#18]
Hello. I'm trying to build Cf-CoAPBench on raspbian and I'm getting the following error when running `mvn -X clean install`: https://gist.github.com/andreibosco/998865fcc0aabcb2a085 (I've put it on gist because of the size of the output log).

**Comment by mkovatsc** [comment]
Based on the the error message, I would say you are using out-of-date code. Do a `git pull`. (Also not that the core package is now in https://github.com/eclipse/californium, so best clone a fresh version of that and install it.

Furthermore, I need to comment that running Cf-CoAPBench does not really make sense on a Raspberry Pi, unless you happen to have hundreds+ of them...

**Comment by sophokles73** [comment]
Doesn't seem to be an issue anymore.
