### ISSUE TITLE
cf-rd cannot register an endpoint to RD with a context in URI query

### ISSUE THREAD

**Issue by navoda** [eclipse/californium.tools#24]
I tried to Register an endpoint to the RD using Third-party registration where a remote client sends a POST request with the endpoint details. 

> Interaction: CLIENT --> RD
> Method: POST
> URI Template: /{+rd}{?ep,d,et,lt,**con**}
>       con := in the form of _scheme://host:port_

This template is according to [CoRE Resource Directory](https://tools.ietf.org/html/draft-ietf-core-resource-directory-08) **6.3 Registration**

As an example 
> Req: POST coap://rd.example.com/rd?ep=node1&d=core&con=coap://localhost:5683

But when **_RDNodeResource_** is using this URI query to add a resource to the RD, regarding the given endpoint, the **con** attribute fails to pass correctly.

I found the class **_LinkAttribute_** (org.eclipse.californium.tools.resources.LinkAttribute) receives the query **con=coap://localhost:5683**  and omits the host and port returning only the schema (in this case **coap**). 

This cause the system to fail to understand the **con** attribute as an actual URI, hence rejects the whole Resource creation.

#### Can you please confirm if this is a bug. If it is, I can send a patch to fix this.

**Comment by sophokles73** [comment]
@navoda,

I am sorry for the delay, I am currently working on multiple other projects and, to be frank, the *Tools* module is not really my *special area of expertise*. I will take a look at it right now and come back to you later ...

**Comment by sophokles73** [comment]
@navoda,

can you check if this is still an issue with the latest commit (57daf9ed768e3865049270ea06e4b51c0097fb52)? I have merged a PR that had been lingering around for some time which also seemed to have addressed this problem.

**Comment by navoda** [comment]
Hi @sophokles73, 
I tried out the RD with the latest commit and it seems the issue has been fixed. Thank you for the quick response. Can I also know when you will have a release with the committed changes?

**Comment by sophokles73** [comment]
Glad this works :-)
Regarding a release, that's a tough question. We haven't really made a plan for a 1.1.0 release yet. However, I do not think that we should wait for too much longer now. So, my feeling currently would be to do a 1.1.0 in November ...

If this issue has been solved for you, can you please close it?
Thanks, Kai
