### ISSUE TITLE
Input fields for PSK credentials.

### ISSUE THREAD

**Issue by boaks** [eclipse/californium.tools#39]
@reichemn

I have to confess, that I have too less experience with javaFx and together with too less time, that results in some gaps. One thing, I would really enjoy to have in this cf-browser would be two fields for PSK credentials (identity (utf-8) and secret (but please without the *** stuff). If you add the fields, I would add that to the PlugPskStore. Just if you're interested and able to spend the time in :-).

**Comment by reichemn** [comment]
@boaks 

Sorry, I also have very little experience with javaFx and at the moment too little time to get used to it.

**Comment by boaks** [comment]
Thanks for your answer!

**Comment by boaks** [comment]
@reichemn 

Just for information:
I managed to extend the Cf-browser, and currently I merged PR #54 , which add that credentials dialog for PSK.
