### ISSUE TITLE
cf-rd with Scandium

### ISSUE THREAD

**Issue by kb2ma** [eclipse/californium.tools#42]
How do I setup/use cf-rd with Scandium in PSK mode? Please point me to the docs if I missed something.

**Comment by kb2ma** [comment]
I was able to hack together a secure RD server, [cf-rdsec](https://github.com/kb2ma/californium.tools/tree/kb2ma-master/cf-rdsec). It's a combination of cf-secure from the Californium demo-apps, and cf-rd from this repository.

I'm sure there is a more elegant way to do it, but I'll need to learn more about the code base first. ;-) At any rate, it's there if someone else needs it.

**Comment by boaks** [comment]
Thanks for your work!

> I'm sure there is a more elegant way to do it

My feeling is, that for now we have no more elegant way :-).
The development focus is more on "libraries" then on "out of the box" services.
If you consider to contribute your extension, you're welcome.
See [contribution](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md)

**Comment by kb2ma** [comment]
Thanks for the confirmation and pointer to contribution guidelines.
